// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function Copy(arg1) {
  return window['go']['main']['App']['Copy'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function PinItem(arg1) {
  return window['go']['main']['App']['PinItem'](arg1);
}
