// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Copy(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<string>>;
