// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory():Promise<void>;

export function Copy(arg1:string):Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function GetHistory():Promise<Array<string>>;

export function PinItem(arg1:number):Promise<void>;
